/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bahan;

/**
 *
 * @author RLB
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login2
     */
    public Login() {
        initComponents();
        show.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hide = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        inputUsername = new javax.swing.JTextField();
        btnBuatAkun = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        template = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hide.setIcon(new javax.swing.ImageIcon("C:\\Users\\RLB\\Downloads\\mdi_hide.png")); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 24, 24));

        show.setIcon(new javax.swing.ImageIcon("C:\\Users\\RLB\\Downloads\\mdi_show.png")); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 24, 24));

        inputPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputPassword.setBorder(null);
        getContentPane().add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 220, -1));

        inputUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputUsername.setBorder(null);
        getContentPane().add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 275, 220, -1));

        btnBuatAkun.setIcon(new javax.swing.ImageIcon("C:\\Users\\RLB\\Downloads\\Buat Akun.png")); // NOI18N
        btnBuatAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuatAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuatAkunMouseClicked(evt);
            }
        });
        getContentPane().add(btnBuatAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 449, 65, 16));

        btnLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\RLB\\Downloads\\Button Login.png")); // NOI18N
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 395, 216, 30));

        template.setIcon(new javax.swing.ImageIcon("C:\\Users\\RLB\\Downloads\\Login.png")); // NOI18N
        getContentPane().add(template, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        show.show();
        hide.hide();
        inputPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_hideMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        hide.show();
        show.hide();
        inputPassword.setEchoChar('*');
    }//GEN-LAST:event_showMouseClicked

    private void btnBuatAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuatAkunMouseClicked
        new Register().show();
        dispose();
    }//GEN-LAST:event_btnBuatAkunMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuatAkun;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel hide;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel show;
    private javax.swing.JLabel template;
    // End of variables declaration//GEN-END:variables
}
