/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PetShop;

/**
 *
 * @author RLB
 */
public class Pasir extends javax.swing.JFrame {

    String namapasir;
    int harga;
    FormBeliPasir fb = new FormBeliPasir();

    public String gumpalsoya[] = {"Blueberry", "Cheese", "Watermelon", "Mango"};
    public String happycat[] = {"Apel", "Lemon", "Coffee", "Strawberry"};
    public String pawsitive[] = {"Apel", "Lemon", "Coffee", "Lavender"};
    public String hoyeow[] = {"Mango", "Grape", "Lemon", "Lavender"};
    public String maxi[] = {"Rose", "Sakura", "Strawberry", "Baby Powder"};
    public String vetsand[] = {"Lemon", "Coffee", "Lavender"};

    /**
     * Creates new form Home
     */
    public Pasir() {
        initComponents();
    }

    private void GumpalSoya() {
        namapasir = "Gumpal Soya";
        harga = 58000;

        fb.namaPasir.setText(namapasir);
        for (String i : gumpalsoya) {
            fb.aroma.addItem(i);
        }
        fb.hargaSatuan.setText("" + harga);
        fb.setVisible(true);
    }

    private void HappyCat() {
        namapasir = "Happy Cat";
        harga = 40000;

        fb.namaPasir.setText(namapasir);
        for (String i : happycat) {
            fb.aroma.addItem(i);
        }
        fb.hargaSatuan.setText("" + harga);
        fb.setVisible(true);
    }

    private void Pawsitive() {
        namapasir = "Pawsitive";
        harga = 115000;

        fb.namaPasir.setText(namapasir);
        for (String i : pawsitive) {
            fb.aroma.addItem(i);
        }
        fb.hargaSatuan.setText("" + harga);
        fb.setVisible(true);
    }

    private void HoYeow() {
        namapasir = "Ho Yeow";
        harga = 80000;

        fb.namaPasir.setText(namapasir);
        for (String i : hoyeow) {
            fb.aroma.addItem(i);
        }
        fb.hargaSatuan.setText("" + harga);
        fb.setVisible(true);
    }

    private void Maxi() {
        namapasir = "Maxi";
        harga = 160000;

        fb.namaPasir.setText(namapasir);
        for (String i : maxi) {
            fb.aroma.addItem(i);
        }
        fb.hargaSatuan.setText("" + harga);
        fb.setVisible(true);
    }

    private void Vetsand() {
        namapasir = "Vetsand";
        harga = 52000;

        fb.namaPasir.setText(namapasir);
        for (String i : vetsand) {
            fb.aroma.addItem(i);
        }
        fb.hargaSatuan.setText("" + harga);
        fb.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pembelian = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        makanan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pasir = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnGumpalSoya = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnHappyCat = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPawsitive = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnHoYeow = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnMaxi = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnVetsand = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        namaUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        penutupToggle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 120, 170));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 120, 170));

        pembelian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pembelian.setForeground(new java.awt.Color(255, 255, 255));
        pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pembelian.png"))); // NOI18N
        pembelian.setText("Pembelian");
        pembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembelianMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 120, 170));

        makanan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        makanan.setForeground(new java.awt.Color(255, 255, 255));
        makanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/makanan.png"))); // NOI18N
        makanan.setText("Makanan");
        makanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        makanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makananMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makanan, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(makanan, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        jPanel3.setBackground(new java.awt.Color(2, 97, 137));

        pasir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pasir.setForeground(new java.awt.Color(255, 255, 255));
        pasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pasir.png"))); // NOI18N
        pasir.setText("Pasir");
        pasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pasir, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pasir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 40));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 720));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gumpal soya.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 150));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("Pasir Kucing Gumpal Soya");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel16.setText("Rp. 58.000");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        btnGumpalSoya.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnGumpalSoya.setText("Beli");
        btnGumpalSoya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGumpalSoya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGumpalSoyaActionPerformed(evt);
            }
        });
        jPanel4.add(btnGumpalSoya, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel22.setText("6 Litter");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 300, 250));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/happy cat.jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 150));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Rp. 40.000");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        btnHappyCat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnHappyCat.setText("Beli");
        btnHappyCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHappyCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHappyCatActionPerformed(evt);
            }
        });
        jPanel5.add(btnHappyCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel17.setText("Pasir Kucing Happy Cat");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel23.setText("10 Litter");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Background.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 300, 250));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pawsitive.jpg"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 150));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Pasir Kucing Pawsitive");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btnPawsitive.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnPawsitive.setText("Beli");
        btnPawsitive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPawsitive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPawsitiveActionPerformed(evt);
            }
        });
        jPanel6.add(btnPawsitive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel19.setText("Rp. 115.000");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel24.setText("25 Litter");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Background.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 300, 250));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ho yeow.jpg"))); // NOI18N
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 150));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel13.setText("Pasir Kucing Ho Yeow");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btnHoYeow.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnHoYeow.setText("Beli");
        btnHoYeow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoYeow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoYeowActionPerformed(evt);
            }
        });
        jPanel7.add(btnHoYeow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel18.setText("Rp. 80.000");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel25.setText("25 Litter");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Background.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 300, 250));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/maxi.jpg"))); // NOI18N
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 150));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setText("Pasir Kucing Maxi");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btnMaxi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnMaxi.setText("Beli");
        btnMaxi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxiActionPerformed(evt);
            }
        });
        jPanel8.add(btnMaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel20.setText("Rp. 160.000");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel26.setText("30 Litter");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Background.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 300, 250));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vetsand.jpg"))); // NOI18N
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 150));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel15.setText("Pasir Kucing Vetsand");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btnVetsand.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnVetsand.setText("Beli");
        btnVetsand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVetsand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVetsandActionPerformed(evt);
            }
        });
        jPanel9.add(btnVetsand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel21.setText("Rp. 52.000");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel27.setText("25 Litter");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Background.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 300, 250));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1366, 720));

        navbar.setBackground(new java.awt.Color(58, 180, 242));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaUser.setForeground(new java.awt.Color(255, 255, 255));
        namaUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaUser.setText("Hello, Admin");
        navbar.add(namaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WIN PETSHOP");
        navbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        penutupToggle.setBackground(new java.awt.Color(58, 180, 242));
        penutupToggle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        penutupToggle.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        navbar.add(penutupToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        bar.setBackground(new java.awt.Color(58, 180, 242));
        bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar.png"))); // NOI18N
        bar.setSelected(true);
        bar.setBorder(null);
        bar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barActionPerformed(evt);
            }
        });
        navbar.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        getContentPane().add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barActionPerformed
        if (bar.isSelected()) {
            sidebar.show();
        } else {
            sidebar.hide();
        }
    }//GEN-LAST:event_barActionPerformed

    private void btnGumpalSoyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGumpalSoyaActionPerformed
        GumpalSoya();
    }//GEN-LAST:event_btnGumpalSoyaActionPerformed

    private void btnHappyCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHappyCatActionPerformed
        HappyCat();
    }//GEN-LAST:event_btnHappyCatActionPerformed

    private void btnPawsitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPawsitiveActionPerformed
        Pawsitive();
    }//GEN-LAST:event_btnPawsitiveActionPerformed

    private void btnHoYeowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoYeowActionPerformed
        HoYeow();
    }//GEN-LAST:event_btnHoYeowActionPerformed

    private void btnMaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxiActionPerformed
        Maxi();
    }//GEN-LAST:event_btnMaxiActionPerformed

    private void btnVetsandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVetsandActionPerformed
        Vetsand();
    }//GEN-LAST:event_btnVetsandActionPerformed

    private void pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianMouseClicked
        new Pembelian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pembelianMouseClicked

    private void makananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makananMouseClicked
        new Makanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_makananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JToggleButton bar;
    private javax.swing.JButton btnGumpalSoya;
    private javax.swing.JButton btnHappyCat;
    private javax.swing.JButton btnHoYeow;
    private javax.swing.JButton btnMaxi;
    private javax.swing.JButton btnPawsitive;
    private javax.swing.JButton btnVetsand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel makanan;
    public javax.swing.JLabel namaUser;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel pasir;
    private javax.swing.JLabel pembelian;
    private javax.swing.JPanel penutupToggle;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
