/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PetShop;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;

/**
 *
 * @author RLB
 */
public class Pembelian extends javax.swing.JFrame {

    private final Connection conn = new Koneksi().konek();
    private Statement st;
    private ResultSet rs;
    private String sql;

    String namamakanan, namapasir, varian, jumlahbeli;
    int hargamakanan, hargapasir, hargasatuan, total;
    DecimalFormat df = new DecimalFormat();

    /**
     * Creates new form Home
     */
    public Pembelian() {
        initComponents();
        dataMakanan();
        totalHargaMakanan();
        dataPasir();
        totalHargaPasir();
        totalSeluruhnya();
    }

    private void dataMakanan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama Makanan");
        model.addColumn("Jumlah");
        model.addColumn("Varian");
        model.addColumn("Harga");

        try {
            sql = "SELECT * FROM makanan";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama_makanan"),
                    rs.getString("jumlah"),
                    rs.getString("varian"),
                    rs.getString("format_harga")
                });
                tabelMakanan.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan data " + e);
        }
    }

    private void totalHargaMakanan() {
        try {
            sql = "SELECT SUM(harga) FROM makanan";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                hargamakanan = rs.getInt("SUM(harga)");
                totalMakanan.setText("Total : Rp. " + df.format(hargamakanan));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan " + e);
        }
    }

    private void dataPasir() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama Pasir");
        model.addColumn("Jumlah");
        model.addColumn("Wangi");
        model.addColumn("Harga");

        try {
            sql = "SELECT * FROM pasir";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama_pasir"),
                    rs.getString("jumlah"),
                    rs.getString("wangi"),
                    rs.getString("format_harga")
                });
                tabelPasir.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan data " + e);
        }
    }

    private void totalHargaPasir() {
        try {
            sql = "SELECT SUM(harga) FROM pasir";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                hargapasir = rs.getInt("SUM(harga)");
                totalPasir.setText("Total : Rp. " + df.format(hargapasir));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan " + e);
        }
    }

    private void totalSeluruhnya() {
        int seluruhnya = hargamakanan + hargapasir;
        totalSeluruhnya.setText("Total Seluruhnya : Rp. " + df.format(seluruhnya));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pembelian = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        makanan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pasir = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMakanan = new javax.swing.JTable();
        totalMakanan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPasir = new javax.swing.JTable();
        totalPasir = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        totalSeluruhnya = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        namaUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        penutupToggle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Petshop");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 120, 170));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 97, 137));

        pembelian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pembelian.setForeground(new java.awt.Color(255, 255, 255));
        pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pembelian.png"))); // NOI18N
        pembelian.setText("Pembelian");
        pembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 120, 170));

        makanan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        makanan.setForeground(new java.awt.Color(255, 255, 255));
        makanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/makanan.png"))); // NOI18N
        makanan.setText("Makanan");
        makanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        makanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makananMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makanan, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(makanan, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        jPanel3.setBackground(new java.awt.Color(0, 120, 170));

        pasir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pasir.setForeground(new java.awt.Color(255, 255, 255));
        pasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pasir.png"))); // NOI18N
        pasir.setText("Pasir");
        pasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pasir, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pasir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 40));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 720));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA PEMBELIAN");
        Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 1120, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pembelian Makanan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tabelMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Makanan", "Jumlah", "Varian", "Harga"
            }
        ));
        tabelMakanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMakananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMakanan);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 500, 250));

        totalMakanan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalMakanan.setText("Total : ");
        Background.add(totalMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 160, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pembelian Pasir", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tabelPasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pasir", "Jumlah", "Wangi", "Harga"
            }
        ));
        tabelPasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPasirMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPasir);

        Background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 500, 250));

        totalPasir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalPasir.setText("Total : ");
        Background.add(totalPasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 360, 160, -1));

        btnKeluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        Background.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 630, -1, -1));

        totalSeluruhnya.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalSeluruhnya.setText("Total Seluruhnya :");
        Background.add(totalSeluruhnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, -1, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1366, 720));

        navbar.setBackground(new java.awt.Color(58, 180, 242));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaUser.setForeground(new java.awt.Color(255, 255, 255));
        namaUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaUser.setText("Hello, Admin");
        navbar.add(namaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WIN PETSHOP");
        navbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        penutupToggle.setBackground(new java.awt.Color(58, 180, 242));
        penutupToggle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        penutupToggle.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        navbar.add(penutupToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        bar.setBackground(new java.awt.Color(58, 180, 242));
        bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar.png"))); // NOI18N
        bar.setSelected(true);
        bar.setBorder(null);
        bar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barActionPerformed(evt);
            }
        });
        navbar.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        getContentPane().add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barActionPerformed
        if (bar.isSelected()) {
            sidebar.show();
        } else {
            sidebar.hide();
        }
    }//GEN-LAST:event_barActionPerformed

    private void makananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makananMouseClicked
        new Makanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_makananMouseClicked

    private void tabelMakananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMakananMouseClicked
        FormUbahMakanan ubah = new FormUbahMakanan();
        ubah.setVisible(true);

        int row = tabelMakanan.getSelectedRow();
        namamakanan = tabelMakanan.getValueAt(row, 0).toString();

        try {
            sql = "SELECT * FROM makanan WHERE nama_makanan='" + namamakanan + "'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                ubah.id = rs.getString("id");
                ubah.namaMakanan.setText(rs.getString("nama_makanan"));
                ubah.hargaSatuan.setText(rs.getString("harga_satuan"));
                ubah.jumlahBeli.setValue(rs.getInt("jumlah"));
            }
            ubah.varianRasa();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan " + e);
        }
    }//GEN-LAST:event_tabelMakananMouseClicked

    private void tabelPasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPasirMouseClicked
        FormUbahPasir ubah = new FormUbahPasir();
        ubah.setVisible(true);

        int row = tabelPasir.getSelectedRow();
        namapasir = tabelPasir.getValueAt(row, 0).toString();

        try {
            sql = "SELECT * FROM pasir WHERE nama_pasir='" + namapasir + "'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                ubah.id = rs.getString("id");
                ubah.namaPasir.setText(rs.getString("nama_pasir"));
                ubah.hargaSatuan.setText(rs.getString("harga_satuan"));
                ubah.jumlahBeli.setValue(rs.getInt("jumlah"));
            }
            ubah.Aroma();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan " + e);
        }
    }//GEN-LAST:event_tabelPasirMouseClicked

    private void pasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasirMouseClicked
        new Pasir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pasirMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar?", "Keluar", JOptionPane.OK_CANCEL_OPTION);
        if (pilihan == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JToggleButton bar;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel makanan;
    public javax.swing.JLabel namaUser;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel pasir;
    private javax.swing.JLabel pembelian;
    private javax.swing.JPanel penutupToggle;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tabelMakanan;
    private javax.swing.JTable tabelPasir;
    private javax.swing.JLabel totalMakanan;
    private javax.swing.JLabel totalPasir;
    private javax.swing.JLabel totalSeluruhnya;
    // End of variables declaration//GEN-END:variables
}
