/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PetShop;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author RLB
 */
public class Register extends javax.swing.JFrame {

    private final Connection conn = new Koneksi().konek();
    private Statement st;
    private ResultSet rs;
    private String sql = "";

    private String nama, Username, password1, password2, nohp;

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
        pass1.setEchoChar((char) 0);
        pass2.setEchoChar((char) 0);
        show1.setVisible(false);
        show2.setVisible(false);
    }

    private void register() {
        nama = String.valueOf(namaLengkap.getText());
        Username = String.valueOf(username.getText());
        password1 = String.valueOf(pass1.getText());
        password2 = String.valueOf(pass2.getText());
        nohp = String.valueOf(noHp.getText());

        if (nama.equals("Nama Lengkap") || Username.equals("Username") || password1.equals("Password") || password2.equals("Konfirmasi Password")) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Pesan", JOptionPane.WARNING_MESSAGE);
        } else if (!password1.equals(password2)) {
            JOptionPane.showMessageDialog(null, "Konfirmasi Password Salah", "Peringatan", JOptionPane.ERROR_MESSAGE);
            pass2.setText("");
        } else {
            try {
                sql = "SELECT * FROM user WHERE username = '" + Username + "'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Username " + rs.getString("username") + " Sudah Ada\nSilahkan Gunakan Username lain.");
                    reset();
                } else {
                    sql = "INSERT INTO user VALUES" + "('" + nama + "', '" + Username + "', md5('" + password1 + "'), '" + nohp + "')";
                    st = conn.createStatement();
                    st.execute(sql);
                    JOptionPane.showMessageDialog(null, "Berhasil Registrasi");
                    Login login = new Login();
                    login.setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Registrasi Gagal!" + e);
            }
        }
    }

    private void reset() {
        namaLengkap.setText("Nama Lengkap");
        namaLengkap.setForeground(new Color(153, 153, 153));
        username.setText("Username");
        username.setForeground(new Color(153, 153, 153));
        pass1.setText("Password");
        pass1.setForeground(new Color(153, 153, 153));
        pass2.setText("Konfirmasi Password");
        pass2.setForeground(new Color(153, 153, 153));
        noHp.setText("No Hp");
        noHp.setForeground(new Color(153, 153, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMasuk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        namaLengkap = new javax.swing.JTextField();
        show1 = new javax.swing.JLabel();
        hide1 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        show2 = new javax.swing.JLabel();
        hide2 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        noHp = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMasuk.setForeground(new java.awt.Color(153, 153, 153));
        btnMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMasuk.setText("Masuk");
        btnMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasukMouseClicked(evt);
            }
        });
        getContentPane().add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 540, 50, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WIN PETSHOP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1366, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lengkapi form pengisian pendaftaran");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 120, 230, 30));

        btnRegister.setBackground(new java.awt.Color(153, 153, 153));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setBorder(null);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 330, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sudah memiliki akun? Silahkan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 200, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Kemudian klik Register");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 230, 30));

        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setText("Username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 300, 40));

        namaLengkap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaLengkap.setForeground(new java.awt.Color(153, 153, 153));
        namaLengkap.setText("Nama Lengkap");
        namaLengkap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaLengkapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaLengkapFocusLost(evt);
            }
        });
        getContentPane().add(namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 300, 40));

        show1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/show.png"))); // NOI18N
        show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show1MouseClicked(evt);
            }
        });
        getContentPane().add(show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 30, 40));

        hide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide.png"))); // NOI18N
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide1MouseClicked(evt);
            }
        });
        getContentPane().add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 30, 40));

        pass1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass1.setForeground(new java.awt.Color(153, 153, 153));
        pass1.setText("Password");
        pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass1FocusLost(evt);
            }
        });
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 300, 40));

        show2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/show.png"))); // NOI18N
        show2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show2MouseClicked(evt);
            }
        });
        getContentPane().add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 30, 40));

        hide2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide.png"))); // NOI18N
        hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide2MouseClicked(evt);
            }
        });
        getContentPane().add(hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 30, 40));

        pass2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass2.setForeground(new java.awt.Color(153, 153, 153));
        pass2.setText("Konfirmasi Password");
        pass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass2FocusLost(evt);
            }
        });
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 300, 40));

        noHp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noHp.setForeground(new java.awt.Color(153, 153, 153));
        noHp.setText("No Hp");
        noHp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                noHpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                noHpFocusLost(evt);
            }
        });
        noHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noHpKeyTyped(evt);
            }
        });
        getContentPane().add(noHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 300, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        register();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMasukMouseClicked

    private void namaLengkapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaLengkapFocusGained
        if (namaLengkap.getText().equals("Nama Lengkap")) {
            namaLengkap.setText("");
            namaLengkap.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_namaLengkapFocusGained

    private void namaLengkapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaLengkapFocusLost
        if (namaLengkap.getText().equals("")) {
            namaLengkap.setText("Nama Lengkap");
            namaLengkap.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_namaLengkapFocusLost

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        if (username.getText().equals("Username")) {
            username.setText("");
            username.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        if (username.getText().equals("")) {
            username.setText("Username");
            username.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_usernameFocusLost

    private void pass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusGained
        if (pass1.getText().equals("Password")) {
            pass1.setText("");
            pass1.setEchoChar('*');
            pass1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pass1FocusGained

    private void pass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusLost
        if (pass1.getText().equals("")) {
            pass1.setText("Password");
            pass1.setEchoChar((char) 0);
            pass1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_pass1FocusLost

    private void pass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusGained
        if (pass2.getText().equals("Konfirmasi Password")) {
            pass2.setText("");
            pass2.setEchoChar('*');
            pass2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pass2FocusGained

    private void pass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusLost
        if (pass2.getText().equals("")) {
            pass2.setText("Konfirmasi Password");
            pass2.setEchoChar((char) 0);
            pass2.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_pass2FocusLost

    private void noHpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noHpFocusGained
        if (noHp.getText().equals("No Hp")) {
            noHp.setText("");
            noHp.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_noHpFocusGained

    private void noHpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noHpFocusLost
        if (noHp.getText().equals("")) {
            noHp.setText("No Hp");
            noHp.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_noHpFocusLost

    private void noHpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noHpKeyTyped
        char angka = evt.getKeyChar();
        if (!Character.isDigit(angka)) {
            JOptionPane.showMessageDialog(null, "Silahkan Masukan Angka", "Pesan", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_noHpKeyTyped

    private void hide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseClicked
        show1.setVisible(true);
        hide1.setVisible(false);
        pass1.setEchoChar((char) 0);
    }//GEN-LAST:event_hide1MouseClicked

    private void show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show1MouseClicked
        hide1.setVisible(true);
        show1.setVisible(false);
        pass1.setEchoChar('*');
    }//GEN-LAST:event_show1MouseClicked

    private void show2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show2MouseClicked
        hide2.setVisible(true);
        show2.setVisible(false);
        pass2.setEchoChar('*');
    }//GEN-LAST:event_show2MouseClicked

    private void hide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MouseClicked
        show2.setVisible(true);
        hide2.setVisible(false);
        pass2.setEchoChar((char) 0);
    }//GEN-LAST:event_hide2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel btnMasuk;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel hide1;
    private javax.swing.JLabel hide2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JTextField noHp;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JLabel show1;
    private javax.swing.JLabel show2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
