/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Komgraf;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RLB
 */
public class AduKekuatan extends javax.swing.JFrame {

    int kekuatankarakter1, kekuatankarakter2;
    String nama1, nama2, result;
    Thread t;

    /**
     * Creates new form AduKekuatan
     */
    public AduKekuatan() {
        initComponents();
        setKarakter();
        Tarung();
    }

    private void setKarakter() {
        nama1 = JOptionPane.showInputDialog(null, "Masukan nama karakter pertama", "Masukan karakter", JOptionPane.QUESTION_MESSAGE);
        nama2 = JOptionPane.showInputDialog(null, "Masukan nama karakter kedua", "Masukan karakter", JOptionPane.QUESTION_MESSAGE);
        namaKarakter1.setText(nama1);
        namaKarakter2.setText(nama2);
    }

    private void Tarung() {
        kekuatankarakter1 = (int) (Math.random() * 101);
        kekuatankarakter2 = (int) (Math.random() * 101);

        Animation();
        result = (kekuatankarakter1 < kekuatankarakter2) ? nama2 + " Menang" : nama1 + " Menang";

        t = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    pemenang.setText("Pemenangnya adalah");
                    Thread.sleep(2500);
                    pemenang.setText(result);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        });
        t.start();
    }

    private void Animation() {
        t = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i <= kekuatankarakter1; i++) {
                        kekuatanKarakter1.setText(i + "");
                        Thread.sleep(30);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        });
        t.start();

        t = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    for (int x = 0; x <= kekuatankarakter2; x++) {
                        kekuatanKarakter2.setText(x + "");
                        Thread.sleep(30);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaKarakter1 = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();
        result1 = new javax.swing.JLabel();
        namaKarakter2 = new javax.swing.JLabel();
        kekuatanKarakter1 = new javax.swing.JLabel();
        kekuatanKarakter2 = new javax.swing.JLabel();
        pemenang = new javax.swing.JLabel();
        btnGantiKarakter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        namaKarakter1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaKarakter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaKarakter1.setText("Karakter1");

        btnRestart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnRestart.setText("Restart");
        btnRestart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        result1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        result1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result1.setText("VS");

        namaKarakter2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaKarakter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaKarakter2.setText("Karakter2");

        kekuatanKarakter1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kekuatanKarakter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kekuatanKarakter1.setText("0");

        kekuatanKarakter2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kekuatanKarakter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kekuatanKarakter2.setText("0");

        pemenang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        pemenang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnGantiKarakter.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnGantiKarakter.setText("Ganti Karakter");
        btnGantiKarakter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGantiKarakter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGantiKarakterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaKarakter1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(result1))
                    .addComponent(kekuatanKarakter1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kekuatanKarakter2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaKarakter2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(pemenang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnRestart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnGantiKarakter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKarakter1)
                    .addComponent(result1)
                    .addComponent(namaKarakter2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kekuatanKarakter1)
                    .addComponent(kekuatanKarakter2))
                .addGap(18, 18, 18)
                .addComponent(pemenang)
                .addGap(30, 30, 30)
                .addComponent(btnRestart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGantiKarakter)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        Tarung();
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnGantiKarakterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGantiKarakterActionPerformed
        setKarakter();
        Tarung();
    }//GEN-LAST:event_btnGantiKarakterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AduKekuatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AduKekuatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AduKekuatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AduKekuatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AduKekuatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGantiKarakter;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel kekuatanKarakter1;
    private javax.swing.JLabel kekuatanKarakter2;
    private javax.swing.JLabel namaKarakter1;
    private javax.swing.JLabel namaKarakter2;
    private javax.swing.JLabel pemenang;
    private javax.swing.JLabel result1;
    // End of variables declaration//GEN-END:variables
}
