/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Komgraf;

/**
 *
 * @author RLB
 */
public class AduKekuatan extends javax.swing.JFrame {

    /**
     * Creates new form AduKekuatan
     */
    public AduKekuatan() {
        initComponents();
        pemenang.setText("" + Tarung(Balmond(), Leomord()));
        kekuatanBalmond.setText("" + Balmond());
        kekuatanLeomord.setText("" + Leomord());
    }

    static int Balmond() {
        int kekuatan = (int) (Math.random() * 101);
        return kekuatan;
    }

    static int Leomord() {
        int kekuatan = (int) (Math.random() * 101);
        return kekuatan;
    }

    private String Tarung(int balmond, int leomord) {
        String result;
//        result = (balmond > leomord) ? "Balmond Menang" : "Leomord Menang";
        if (balmond > leomord) {
            result = "Balmond Menang";
        } else {
            result = "Leomord Menang";
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();
        result1 = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();
        kekuatanBalmond = new javax.swing.JLabel();
        kekuatanLeomord = new javax.swing.JLabel();
        pemenang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel.setText("Balmond");

        btnRestart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnRestart.setText("Restart");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        result1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        result1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result1.setText("VS");

        result2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        result2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result2.setText("Leomord");

        kekuatanBalmond.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kekuatanBalmond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kekuatanBalmond.setText("0");

        kekuatanLeomord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kekuatanLeomord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kekuatanLeomord.setText("0");

        pemenang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        pemenang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pemenang.setText("Pemenang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(kekuatanBalmond)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kekuatanLeomord)
                            .addGap(29, 29, 29))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(JLabel)
                            .addGap(37, 37, 37)
                            .addComponent(result1)
                            .addGap(46, 46, 46)
                            .addComponent(result2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnRestart)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addComponent(pemenang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel)
                    .addComponent(result1)
                    .addComponent(result2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kekuatanBalmond)
                    .addComponent(kekuatanLeomord))
                .addGap(18, 18, 18)
                .addComponent(pemenang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnRestart)
                .addGap(80, 80, 80))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        new AduKekuatan().show();
        this.dispose();
    }//GEN-LAST:event_btnRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AduKekuatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AduKekuatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AduKekuatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AduKekuatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AduKekuatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel kekuatanBalmond;
    private javax.swing.JLabel kekuatanLeomord;
    private javax.swing.JLabel pemenang;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel result2;
    // End of variables declaration//GEN-END:variables
}
