/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Komgraf;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author RLB
 */
public class Drawing extends javax.swing.JFrame {

    /**
     * Creates new form Drawing
     */
    public Drawing() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        g.setColor(Color.gray);
        g.fillArc(220, 100, 150, 150, 0, 360);//Kepala

        g.setColor(Color.white);
        g.fillArc(234, 130, 60, 60, 0, 360);//Mata kiri
        g.fillArc(296, 130, 60, 60, 0, 360);//Mata kanan

        g.setColor(Color.black);
        g.fillArc(253, 150, 20, 20, 0, 360);//Bola mata kiri
        g.fillArc(317, 150, 20, 20, 0, 360);//Bola mata kanan
        g.fillArc(285, 180, 20, 20, 0, 360);//Hidung
        g.fillArc(260, 170, 70, 70, 180, 180);//Mulut
        g.drawLine(220, 180, 200, 80);//Kuping kiri
        g.drawLine(200, 80, 280, 100);//Kuping kiri
        g.drawLine(370, 180, 390, 80);//Kuping kanan
        g.drawLine(390, 80, 310, 100);//Kuping kanan

        g.setColor(Color.red);
        g.fillArc(277, 204, 35, 35, 180, 180);//Lidah

        g.setColor(Color.black);
        g.fillArc(243, 250, 110, 125, 0, 360);//Badan
        g.fillRect(190, 280, 70, 20);//Tangan kiri
        g.fillArc(170, 265, 30, 50, 0, 360);//Tangan kiri
        g.fillRect(340, 280, 70, 20);//Tangan kanan
        g.fillArc(395, 265, 30, 50, 0, 360);//Tangan kanan

        g.setColor(Color.gray);
        g.fillArc(260, 280, 75, 75, 0, 360);//Perut

        g.setColor(Color.black);
        g.fillRect(263, 360, 20, 70);//Kaki kiri
        g.fillArc(235, 410, 50, 30, 0, 360);//Kaki kiri
        g.fillRect(313, 360, 20, 70);//Kaki kanan
        g.fillArc(310, 410, 50, 30, 0, 360);//Kaki kanan
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kucing Nyengir");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(616, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drawing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
