/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Komgraf;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author RLB
 */
public class SplashScreen extends javax.swing.JFrame {

    Thread t;

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        loadingProgress();
        persentaseLoading();
    }

    private void loadingProgress() {
        t = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 570; i++) {
                    try {
                        loadingProgress.setPreferredSize(new Dimension(i, 7));
                        spam.setText(i + "");
                        spam.hide();
                        Thread.sleep(8);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
            }
        });
        t.start();
    }

    private void persentaseLoading() {
        t = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    try {
                        persentaseLoading.setText("Loading... " + i + "%");
                        Thread.sleep(50);
                        if (i == 100) {
                            Thread.sleep(1000);
                            dispose();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        copyright = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        loadingProgress = new javax.swing.JPanel();
        persentaseLoading = new javax.swing.JLabel();
        spam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(173, 142, 112));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        copyright.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 235, 183));
        copyright.setText("Copyright © 2023, Rayhan Lingga Buana");
        background.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 369, 780, -1));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\RLB\\Downloads\\splash.png")); // NOI18N
        background.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 800, 260));

        loadingProgress.setBackground(new java.awt.Color(36, 55, 99));

        javax.swing.GroupLayout loadingProgressLayout = new javax.swing.GroupLayout(loadingProgress);
        loadingProgress.setLayout(loadingProgressLayout);
        loadingProgressLayout.setHorizontalGroup(
            loadingProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        loadingProgressLayout.setVerticalGroup(
            loadingProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        background.add(loadingProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 317, -1, -1));

        persentaseLoading.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        persentaseLoading.setForeground(new java.awt.Color(255, 235, 183));
        persentaseLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        persentaseLoading.setText("Loading... 0%");
        background.add(persentaseLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 279, 570, -1));
        background.add(spam, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel image;
    private javax.swing.JPanel loadingProgress;
    private javax.swing.JLabel persentaseLoading;
    private javax.swing.JLabel spam;
    // End of variables declaration//GEN-END:variables
}
