/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProgramSederhana;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RLB
 */
public class PetShop extends javax.swing.JFrame {

    int harga;
    DefaultTableModel model;
    Timer time;
    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss"); //Jam
    SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MMM-yyyy"); //Tanggal
    String jam, tanggal, totalHarga;
    DecimalFormat df = new DecimalFormat();

    /**
     * Creates new form PetShop
     */
    public PetShop() {
        initComponents();
        String[] title = {"Tanggal", "jam", "Nama Pemilik", "Nama Kucing", "Jenis Kelamin", "Jenis Mandi", "Harga"};
        model = new DefaultTableModel(title, 0);
        tabeldata.setModel(model);
        tampilkan();
        Time();
    }

    private void Time() {
        time = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                jam = sdf.format(date);
                tanggal = sdf2.format(date);
            }
        });
        time.start();
    }

    private void tampilkan() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/petshop", "root", "");
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM datapelanggan";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] obj = new Object[7];
                obj[0] = rs.getString("tanggal");
                obj[1] = rs.getString("jam");
                obj[2] = rs.getString("nama_pemilik");
                obj[3] = rs.getString("nama_kucing");
                obj[4] = rs.getString("jenis_kelamin");
                obj[5] = rs.getString("jenis_mandi");
                obj[6] = rs.getString("harga");
                model.addRow(obj);
            }
        } catch (Exception e) {
            System.out.println("Terjadi Kesalahan");
        }
    }

    private void hargaMandi() {
        String mandi = String.valueOf(jenisMandi.getSelectedItem());

        if (mandi == "Mandi Biasa") {
            harga = 50000;
        } else if (mandi == "Mandi Kutu") {
            harga = 60000;
        } else if (mandi == "Mandi Lengkap") {
            harga = 70000;
        } else {
            harga = 90000;
        }
        totalHarga = "Rp. " + df.format(harga);
    }

    private void reset() {
        namaPemilik.setText("");
        namaKucing.setText("");
        jenisKelamin.setSelectedItem("Jantan");
        jenisMandi.setSelectedItem("Mandi Biasa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaPemilik = new javax.swing.JTextField();
        namaKucing = new javax.swing.JTextField();
        jenisKelamin = new javax.swing.JComboBox<>();
        jenisMandi = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        btnOke = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setPreferredSize(new java.awt.Dimension(1130, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel1.setText("CLEAN PETSHOP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Nama Pemilik");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Nama Kucing");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setText("Jenis Mandi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, -1, -1));

        namaPemilik.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(namaPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 73, 155, -1));

        namaKucing.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(namaKucing, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 119, 155, -1));

        jenisKelamin.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jantan", "Betina" }));
        jenisKelamin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 165, 155, -1));

        jenisMandi.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jenisMandi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mandi Biasa", "Mandi Kutu", "Mandi Lengkap", "Mandi + Cukur" }));
        jenisMandi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jenisMandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisMandiActionPerformed(evt);
            }
        });
        getContentPane().add(jenisMandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 211, 155, -1));

        tabeldata.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Jam", "Nama Pemilik", "Nama Kucing", "Jenis Kelamin", "Jenis Mandi", "Harga"
            }
        ));
        tabeldata.setRowHeight(20);
        jScrollPane3.setViewportView(tabeldata);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 70, 720, 380));

        btnOke.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnOke.setText("OKE");
        btnOke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeActionPerformed(evt);
            }
        });
        getContentPane().add(btnOke, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, 333, -1));

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/bg.jpg"))); // NOI18N
        getContentPane().add(BACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeActionPerformed
        hargaMandi();
        String namapemilik = namaPemilik.getText();
        String namakucing = namaKucing.getText();
        String jeniskelamin = String.valueOf(jenisKelamin.getSelectedItem());
        String jenismandi = String.valueOf(jenisMandi.getSelectedItem());

        try {
            if (namapemilik.equals("") || namakucing.equals("")) {
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/petshop", "root", "");
                Statement st = conn.createStatement();
                String sql = "INSERT INTO datapelanggan VALUES" + "('" + tanggal + "','" + jam + "','" + namapemilik + "','" + namakucing + "','" + jeniskelamin + "','" + jenismandi + "', '" + totalHarga + "')";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Anda Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                tampilkan();
                reset();
            }
        } catch (Exception e) {
            System.out.println("Terjadi Kesalahan");
        }
    }//GEN-LAST:event_btnOkeActionPerformed

    private void jenisMandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisMandiActionPerformed

    }//GEN-LAST:event_jenisMandiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton btnOke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> jenisKelamin;
    private javax.swing.JComboBox<String> jenisMandi;
    private javax.swing.JTextField namaKucing;
    private javax.swing.JTextField namaPemilik;
    private javax.swing.JTable tabeldata;
    // End of variables declaration//GEN-END:variables

}
